# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Styx < Formula
  desc "Terminal agent harness for coding plus security work, with harness-enforced dual-mode safety"
  homepage "https://github.com/mobley-trent/styx-agent"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.2.1/styx_0.2.1_darwin_amd64.tar.gz"
      sha256 "a30bdd76cf55001f3dc546c78062206279faa69b59077d7ee6343c0145a22475"

      define_method(:install) do
        bin.install "styx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.2.1/styx_0.2.1_darwin_arm64.tar.gz"
      sha256 "7c5bb5a90f0c10725b0518a664f242c2ae1bb0ee2e6e9c1afff07c002e18e8aa"

      define_method(:install) do
        bin.install "styx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.2.1/styx_0.2.1_linux_amd64.tar.gz"
      sha256 "60176f2af67b885606ae1190a5d332d9ff96d2b871556df3fd9c58558088ce9f"
      define_method(:install) do
        bin.install "styx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.2.1/styx_0.2.1_linux_arm64.tar.gz"
      sha256 "834b5db39b2624e2c2c199bebb0815039ca27f05c0cdf8c32a61e050befba3e5"
      define_method(:install) do
        bin.install "styx"
      end
    end
  end

  test do
    system "#{bin}/styx", "--version"
  end
end
