# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Styx < Formula
  desc "Terminal agent harness for coding plus security work, with harness-enforced dual-mode safety"
  homepage "https://github.com/mobley-trent/styx-agent"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.1.0/styx_0.1.0_darwin_amd64.tar.gz"
      sha256 "5ced7095927935cb8c8f4d9cb3a58057e9bf4b97c93b5d5867d26a608a92e6d8"

      define_method(:install) do
        bin.install "styx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.1.0/styx_0.1.0_darwin_arm64.tar.gz"
      sha256 "c2115cff69deb9b5a13228cb2f52249e1a88dae2f16c1f755e8b15714b6ac8ab"

      define_method(:install) do
        bin.install "styx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.1.0/styx_0.1.0_linux_amd64.tar.gz"
      sha256 "4fb13e152b3479370fd1c15a40b7d0ac0bad41beb5d8fa558b74bdffc845131b"
      define_method(:install) do
        bin.install "styx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mobley-trent/styx-agent/releases/download/v0.1.0/styx_0.1.0_linux_arm64.tar.gz"
      sha256 "cf6085d42133ec666dc6fddce36dce1e46611f02bb371325e26fe17309a4137f"
      define_method(:install) do
        bin.install "styx"
      end
    end
  end

  test do
    system "#{bin}/styx", "--version"
  end
end
